const ACCOUNT_TYPES = {
  FETCH_GIVENOFFERS_START: 'FETCH_GIVENOFFERS_START',
  FETCH_GIVENOFFERS_SUCCESS: 'FETCH_GIVENOFFERS_SUCCESS',
  FETCH_GIVENOFFERS_ERROR: 'FETCH_GIVENOFFERS_ERROR',
  FETCH_RECEIVEDOFFERS_START: 'FETCH_RECEIVEDOFFERS_START',
  FETCH_RECEIVEDOFFERS_SUCCESS: 'FETCH_RECEIVEDOFFERS_SUCCESS',
  FETCH_RECEIVEDOFFERS_ERROR: 'FETCH_RECEIVEDOFFERS_ERROR',
  FETCH_REJECTOFFER_START: 'FETCH_REJECTOFFER_START',
  FETCH_REJECTOFFER_SUCCESS: 'FETCH_REJECTOFFER_SUCCESS',
  FETCH_REJECTOFFER_ERROR: 'FETCH_REJECTOFFER_ERROR',
  FETCH_ACCEPTOFFER_START: 'FETCH_ACCEPTOFFER_START',
  FETCH_ACCEPTOFFER_SUCCESS: 'FETCH_ACCEPTOFFER_SUCCESS',
  FETCH_ACCEPTOFFER_ERROR: 'FETCH_ACCEPTOFFER_ERROR',
  FETCH_CANCELOFFER_START: 'FETCH_CANCELOFFER_START',
  FETCH_CANCELOFFER_SUCCESS: 'FETCH_CANCELOFFER_SUCCESS',
  FETCH_CANCELOFFER_ERROR: 'FETCH_CANCELOFFER_ERROR',
};
export default ACCOUNT_TYPES;
