const AUTH_TYPES = {
  FETCH_SIGNIN_START: 'FETCH_SIGNIN_START',
  FETCH_SIGNIN_SUCCESS: 'FETCH_SIGNIN_SUCCESS',
  FETCH_SIGNIN_ERROR: 'FETCH_SIGNIN_ERROR',
  FETCH_SIGNUP_START: 'FETCH_SIGNUP_START',
  FETCH_SIGNUP_SUCCESS: 'FETCH_SIGNUP_SUCCESS',
  FETCH_SIGNUP_ERROR: 'FETCH_SIGNUP_ERROR',
  SIGNIN_LOG_OUT: 'SIGNIN_LOG_OUT',
  SIGNUP_LOG_OUT: 'SIGNUP_LOG_OUT',
};
export default AUTH_TYPES;
