const BRAND_TYPES = {
  FETCH_ALLBRANDS_START: 'FETCH_ALLBRANDS_START',
  FETCH_ALLBRANDS_SUCCESS: 'FETCH_ALLBRANDS_SUCCESS',
  FETCH_ALLBRANDS_ERROR: 'FETCH_ALLBRANDS_ERROR',
  FETCH_GETBRAND_START: 'FETCH_GETBRAND_START',
  FETCH_GETBRAND_SUCCESS: 'FETCH_GETBRAND_SUCCES',
  FETCH_GETBRAND_ERROR: 'FETCH_GETBRAND_ERROR',
};
export default BRAND_TYPES;
