const CATEGORY_TYPES = {
  FETCH_ALLCATEGORIES_START: 'FETCH_ALLCATEGORIES_START',
  FETCH_ALLCATEGORIES_SUCCESS: 'FETCH_ALLCATEGORIES_SUCCES',
  FETCH_ALLCATEGORIES_ERROR: 'FETCH_ALLCATEGORIES_ERROR',
  FETCH_GETCATEGORY_START: 'FETCH_GETCATEGORY_START',
  FETCH_GETCATEGORY_SUCCESS: 'FETCH_GETCATEGORY_SUCCES',
  FETCH_GETCATEGORY_ERROR: 'FETCH_GETCATEGORY_ERROR',
};
export default CATEGORY_TYPES;
