const COLOR_TYPES = {
  FETCH_ALLCOLORS_START: 'FETCH_ALLCOLORS_START',
  FETCH_ALLCOLORS_SUCCESS: 'FETCH_ALLCOLORS_SUCCESS',
  FETCH_ALLCOLORS_ERROR: 'FETCH_ALLCOLORS_ERROR',
  FETCH_GETCOLOR_START: 'FETCH_GETCOLOR_START',
  FETCH_GETCOLOR_SUCCESS: 'FETCH_GETCOLOR_SUCCESS',
  FETCH_GETCOLOR_ERROR: 'FETCH_GETCOLOR_ERROR',
};
export default COLOR_TYPES;
