const FILE_TYPES = {
  FETCH_UPLOADIMAGE_START: 'FETCH_UPLOADIMAGE_START',
  FETCH_UPLOADIMAGE_SUCCESS: 'FETCH_UPLOADIMAGE_SUCCES',
  FETCH_UPLOADIMAGE_ERROR: 'FETCH_UPLOADIMAGE_ERROR',
  FETCH_UPLOADIMAGE_PERCENT: 'FETCH_UPLOADIMAGE_PERCENT',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
};
export default FILE_TYPES;
