const FILE_TYPES = {
  FETCH_UPLOADIMAGE_START: 'FETCH_UPLOADIMAGE_START',
  FETCH_UPLOADIMAGE_SUCCESS: 'FETCH_UPLOADIMAGE_SUCCES',
  FETCH_UPLOADIMAGE_ERROR: 'FETCH_UPLOADIMAGE_ERROR',
};
export default FILE_TYPES;
