const PRODUCT_TYPES = {
  FETCH_ALLPRODUCTS_START: 'FETCH_ALLPRODUCTS_START',
  FETCH_ALLPRODUCTS_SUCCESS: 'FETCH_ALLPRODUCTS_SUCCES',
  FETCH_ALLPRODUCTS_ERROR: 'FETCH_ALLPRODUCTS_ERROR',
  FETCH_GETPRODUCT_START: 'FETCH_GETPRODUCT_START',
  FETCH_GETPRODUCT_SUCCESS: 'FETCH_GETPRODUCT_SUCCES',
  FETCH_GETPRODUCT_ERROR: 'FETCH_GETPRODUCT_ERROR',
};
export default PRODUCT_TYPES;
