const PRODUCT_TYPES = {
  FETCH_ALLPRODUCTS_START: 'FETCH_ALLPRODUCTS_START',
  FETCH_ALLPRODUCTS_SUCCESS: 'FETCH_ALLPRODUCTS_SUCCESS',
  FETCH_ALLPRODUCTS_ERROR: 'FETCH_ALLPRODUCTS_ERROR',
  FETCH_GETPRODUCT_START: 'FETCH_GETPRODUCT_START',
  FETCH_GETPRODUCT_SUCCESS: 'FETCH_GETPRODUCT_SUCCES',
  FETCH_GETPRODUCT_ERROR: 'FETCH_GETPRODUCT_ERROR',
  FETCH_CREATEPRODUCT_START: 'FETCH_CREATEPRODUCT_START',
  FETCH_CREATEPRODUCT_SUCCESS: 'FETCH_CREATEPRODUCT_SUCCESS',
  FETCH_CREATEPRODUCT_ERROR: 'FETCH_CREATEPRODUCT_ERROR',
  FETCH_OFFERPRODUCT_START: 'FETCH_OFFERPRODUCT_START',
  FETCH_OFFERPRODUCT_SUCCESS: 'FETCH_OFFERPRODUCT_SUCCESS',
  FETCH_OFFERPRODUCT_ERROR: 'FETCH_OFFERPRODUCT_ERROR',
  FETCH_PURCHASEPRODUCT_START: 'FETCH_PURCHASEPRODUCT_START',
  FETCH_PURCHASEPRODUCT_SUCCESS: 'FETCH_PURCHASEPRODUCT_SUCCESS',
  FETCH_PURCHASEPRODUCT_ERROR: 'FETCH_PURCHASEPRODUCT_ERROR',
  REDIRECT_PRODUCT: 'REDIRECT_PRODUCT',
};
export default PRODUCT_TYPES;
