const STATUS_TYPES = {
  FETCH_ALLSTATUSES_START: 'FETCH_ALLSTATUSES_START',
  FETCH_ALLSTATUSES_SUCCESS: 'FETCH_ALLSTATUSES_SUCCESS',
  FETCH_ALLSTATUSES_ERROR: 'FETCH_ALLSTATUSES_ERROR',
  FETCH_GETSTATUS_START: 'FETCH_GETSTATUS_START',
  FETCH_GETSTATUS_SUCCESS: 'FETCH_GETSTATUS_SUCCES',
  FETCH_GETSTATUS_ERROR: 'FETCH_GETSTATUS_ERROR',
};
export default STATUS_TYPES;
