const STATUS_TYPES = {
  FETCH_ALLSTATUS_START: 'FETCH_ALLSTATUS_START',
  FETCH_ALLSTATUS_SUCCESS: 'FETCH_ALLSTATUS_SUCCESS',
  FETCH_ALLSTATUS_ERROR: 'FETCH_ALLSTATUS_ERROR',
  FETCH_GETSTATUS_START: 'FETCH_GETSTATUS_START',
  FETCH_GETSTATUS_SUCCESS: 'FETCH_GETSTATUS_SUCCESS',
  FETCH_GETSTATUS_ERROR: 'FETCH_GETSTATUS_ERROR',
};
export default STATUS_TYPES;
